# Build only the reconstructed one-core 300 MHz BS1 reference.
# Usage: vivado -mode batch -source build_bs1_reference.tcl -tclargs NEW_OUTPUT_DIR
# Requires Vivado with the VU9P part and JTAG-to-AXI IP installed.
# Never programs hardware. Generated bytes are not the archived BS1 bitstream.
if {[llength $argv] != 1} { error "expected a new output directory" }
set here [file dirname [file normalize [info script]]]
set out [file normalize [lindex $argv 0]]
if {[file exists $out]} { error "output directory must not already exist" }
set inputs {}
foreach name {keccak_round_c.v sha3t_pipe.v sha3t_core1.v axil_regfile.v sha3t_top.v} {
    set path [file join $here rtl $name]
    if {![file isfile $path]} { error "missing reference RTL: $name" }
    lappend inputs $path
}
set constraints [file join $here bs1_reference.xdc]
if {![file isfile $constraints]} { error "missing reference constraints" }
create_project bs1_reference [file join $out project] -part xcvu9p-fsgd2104-2L-e
set_property target_language Verilog [current_project]
add_files $inputs
set_property top sha3t_top [current_fileset]
add_files -fileset constrs_1 $constraints
create_ip -name jtag_axi -vendor xilinx.com -library ip -version 1.2 -module_name jtag_axi_0
set_property CONFIG.PROTOCOL 2 [get_ips jtag_axi_0]
generate_target all [get_ips jtag_axi_0]
launch_runs synth_1 -jobs 4
wait_on_run synth_1
if {[get_property PROGRESS [get_runs synth_1]] ne "100%"} { error "reference synthesis failed" }
launch_runs impl_1 -to_step route_design -jobs 4
wait_on_run impl_1
if {[get_property PROGRESS [get_runs impl_1]] ne "100%"} { error "reference routing failed" }
open_run impl_1
report_utilization -file [file join $out utilization.rpt]
report_timing_summary -file [file join $out timing.rpt]
report_route_status -file [file join $out route_status.rpt]
report_drc -file [file join $out drc.rpt]
set wns [get_property STATS.WNS [get_runs impl_1]]
set whs [get_property STATS.WHS [get_runs impl_1]]
foreach slack [list $wns $whs] {
    if {![string is double -strict $slack] || [regexp -nocase {nan|inf} $slack] || $slack < 0} {
        error "reference reported setup/hold timing did not pass"
    }
}
write_bitstream [file join $out bc3_vu9p_bs1_reference_300mhz.bit]
puts "BS1_REFERENCE_BUILD_COMPLETE core_count=1 nominal_mhz=300 hardware_qualification=NOT_PERFORMED archival_reproduction=NOT_CLAIMED"
