/*
 * hash_test.c - Send known work to FPGA and compare hash output
 *
 * Uses the real mining bitstream. Sends known CV + block2 data,
 * waits for the FPGA to hash nonce=0, reads back hash7, compares.
 */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <libusb-1.0/libusb.h>

extern void blake3_compress_host(const uint32_t cv[8], const uint32_t bw[16],
    uint64_t counter, uint32_t block_len, uint32_t flags, uint32_t out[8]);

static int ztex_send(libusb_device_handle *h, unsigned char *buf, int len) {
    int idx = 0;
    while (len > 0) {
        int chunk = len > 64 ? 64 : len;
        int r = libusb_control_transfer(h, 0x40, 0x80, 0, 0, buf + idx, chunk, 2000);
        if (r < 0) { printf("Send error: %d\n", r); return r; }
        len -= r; idx += r;
    }
    return idx;
}

static int ztex_read(libusb_device_handle *h, uint32_t *golden1, uint32_t *nonce,
                     uint32_t *hash7, uint32_t *golden2) {
    unsigned char rbuf[16];
    int ret = 16, len = 0;
    while (ret > 0) {
        int r = libusb_control_transfer(h, 0xc0, 0x81, 0, 0, rbuf + len, ret, 1000);
        if (r < 0) return r;
        ret -= r; len += r;
    }
    memcpy(golden1, rbuf, 4);
    memcpy(nonce, rbuf+4, 4);
    memcpy(hash7, rbuf+8, 4);
    memcpy(golden2, rbuf+12, 4);
    return len;
}

int main() {
    /* Known CV (from test_compress: all-zeros 180-byte header) */
    uint32_t cv[8];
    uint32_t iv[8] = {0x6A09E667,0xBB67AE85,0x3C6EF372,0xA54FF53A,
                      0x510E527F,0x9B05688C,0x1F83D9AB,0x5BE0CD19};
    uint32_t bw[16] = {0};
    uint32_t cv0[8];
    blake3_compress_host(iv, bw, 0, 64, 1, cv0);
    blake3_compress_host(cv0, bw, 0, 64, 0, cv);

    printf("CV: ");
    for (int i=7;i>=0;i--) printf("%08X",cv[i]);
    printf("\n");

    /* Block 2 words (all zero, nonce=0 will be generated by FPGA core 0) */
    uint32_t b2_low[3] = {0, 0, 0};  /* m[0], m[1], m[2] */
    uint32_t b2_high[9] = {0};        /* m[4]..m[12] */
    uint32_t target = 0xFFFFFFFF;      /* easy target */

    /* Pack 84-byte buffer (raw LE, no manipulation) */
    unsigned char data[84];
    memcpy(data, cv, 32);
    memcpy(data+32, b2_low, 12);
    memcpy(data+44, b2_high, 36);
    memcpy(data+80, &target, 4);

    printf("Data[0..3]: %02X %02X %02X %02X (CV[0]=%08X)\n",
        data[0],data[1],data[2],data[3], cv[0]);

    /* Compute expected hash7 for nonce=0,4,8,12 */
    uint32_t b2[16] = {0};
    for (int n = 0; n <= 12; n += 4) {
        b2[3] = n;
        uint32_t h[8];
        blake3_compress_host(cv, b2, 0, 52, 2|8, h);
        printf("SW: nonce=%d hash7=%08X\n", n, h[7]);
    }

    /* Open USB */
    libusb_context *ctx;
    libusb_init(&ctx);
    libusb_device_handle *h = libusb_open_device_with_vid_pid(ctx, 0x221a, 0x0100);
    if (!h) { fprintf(stderr, "Cannot open ZTEX\n"); return 1; }
    libusb_claim_interface(h, 0);

    /* Select FPGA 0 */
    libusb_control_transfer(h, 0x40, 0x82, 0, 0, NULL, 0, 1000);

    /* Send work */
    printf("\nSending 84 bytes...\n");
    ztex_send(h, data, 84);

    /* Read back multiple times */
    for (int i = 0; i < 10; i++) {
        usleep(200000);
        uint32_t g1, nonce, h7, g2;
        ztex_read(h, &g1, &nonce, &h7, &g2);
        printf("Read %d: nonce=%08X hash7=%08X golden1=%08X golden2=%08X\n",
            i, nonce, h7, g1, g2);

        /* Try to match hash7 with any nonce */
        for (uint32_t try_n = 0; try_n < nonce + 16; try_n += 4) {
            b2[3] = try_n;
            uint32_t th[8];
            blake3_compress_host(cv, b2, 0, 52, 2|8, th);
            if (th[7] == h7) {
                printf("  >>> MATCH at nonce=%d (0x%X)! <<<\n", try_n, try_n);
                break;
            }
        }
    }

    libusb_release_interface(h, 0);
    libusb_close(h);
    libusb_exit(ctx);
    return 0;
}
